### PR TITLE
Fixup example to use JS conventions

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Note, `declinationAngle` is not defined?

**Comment by riju** [comment]
Thanks for the fix. yes, `declinationAngle`is not defined, but just above the example, we have defined what `declinationAngle` angle is and how we can get the value.
Maybe add a comment in the example code saying that, or even initializing with a dummy value for a popular location (San Francisco = + 13° 38' ).

**Comment by marcoscaceres** [comment]
> San Francisco = + 13° 38' 
How do I express that as JS?

**Comment by anssiko** [comment]
Doing some house cleaning, I noticed the spec had actually fixed itself per conventions suggested in this PR by @marcoscaceres (use short names, camelCase), so we can close this PR. Anyway, thanks!

**Pull request closed without merging**
